### ISSUE TITLE
Text around Dots don't work

### ISSUE THREAD

**Issue by frankNaruhn** [dev-cycles/contextive#105]
**Describe the bug**
When using dots in the description the tool/lanuage server breaks.

**To Reproduce**
Use the following something.glossary.yml:

```
contexts:
  - name: someContext
    terms:
      - name: working
        definition: "this is 'working'. Normal '.' do work."
      - name: not
        definition: "this is 'not'. Because of some weird regexp i guess: a.a"
```

**Expected behavior**
"Working" and "notWorking" are both working :P

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.16.2
 - Intellij Plugin

![Image](https://github.com/user-attachments/assets/07914985-ba9e-42be-b2ef-12ab8f13026d)

**Comment by chrissimon-au** [comment]
Thanks for reporting this - interestingly, it doesn't happen in VsCode.

![Image](https://github.com/user-attachments/assets/71a9dae4-2676-4008-b809-d49b60d85234)

However I have been able to replicate in the IntelliJ platform.  I believe it's likely to do with their markdown rendering - since we pass in the `description` field as is so that you can include markdown like `_italic_` and `1. bullet points` etc.

I know some markdown renderers have an issue with a period character (`.`) because it confuses the issue with numbered and unnumbered lists.

As a workaround, you can escape the period like so:

```
contexts:
  - name: someContext
    terms:
      - name: working
        definition: "this is 'working'. Normal '.' do work."
      - name: not
        definition: "this is 'not'. Because of some weird regexp i guess: a\\.a"
```

The reason you need a double-escape is we need to emit in markdown: `this is 'not'. Because of some weird regexp i guess: a\.a` but if we just put that in the yaml, then the yaml parser thinks we are escaping the `.` which isn't valid yaml.  So we need to escape the `\`.

After parsing the yaml, we end up with: `this is 'not'. Because of some weird regexp i guess: a\.a` - See [Yaml Escaping](https://yaml.org/spec/1.2.2/#57-escaped-characters)

After rendering that as markdown, we end up with: `this is 'not'. Because of some weird regexp i guess: a.a` - See [Markdown backslash escapes](https://spec.commonmark.org/0.31.2/#backslash-escapes)

However, I will raise this on the intelliJ youtrack, as I believe their markdown rendering should be resilient to this situation, as VsCode's is.

I don't want to automatically escape periods in the description text, because that would block folks' ability to use proper numbered lists in their descriptions.
